version: '3.1'

services:

  mongo:
    image: mongo
    container_name: kwwqxmokvrqzdaaspscp_mongo_1
    restart: always
    ports:
      - "27018:27017"

  postgres:
    image: postgres
    container_name: postgres-11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local
    ports:
      - "2023:5432"
