server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
      gridfs:
        database: greetgo
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:2023/postgres
  liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: create-drop
h2:
  console:
    enabled: false
