server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: myDatabase
      username: rootuser
      password: rootpass
      gridfs:
        database: mongodb
  liquibase:
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
